services:
  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vectorexample

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    # Uncomment this line if you want the app service to share the same network namespace as the postgres service
    # network_mode: service:postgres 

volumes:
  postgres_data:  # Ensure this volume is correctly named and defined

# services:
#   postgres:
#     build:
#       context: ./postgres
#       dockerfile: postgres.Dockerfile
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql

#     environment:
#         - POSTGRES_USER=postgres
#         - POSTGRES_PASSWORD=postgres
#         - POSTGRES_DB=vectorexample
  
#   app:
#     build:
#       context: ..
#       dockerfile: .devcontainer/Dockerfile
#     volumes:
#       - ../..:/workspaces:cached
#     # Overrides default command so things don't shut down after the process ends.
#     command: sleep infinity

#     # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
#     #network_mode: service:db

#     # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
#     # (Adding the "ports" property to this file will not forward from a Codespace.)

# #   # Example I found online ...
# #   db:
# #   #   hostname: db
# #   #   image: ankane/pgvector
# #   #   ports:
# #   #    - 5432:5432
# #   #   restart: always
# #   #   environment:
# #   #     POSTGRES_DB: vectordb
# #   #     POSTGRES_USER: testuser
# #   #     POSTGRES_PASSWORD: testpwd
# #   #     POSTGRES_HOST_AUTH_METHOD: trust
# #   #   volumes:
# #   #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# #     image: postgres:latest
# #     restart: unless-stopped
# #     volumes:
# #       - postgres-data:/var/lib/postgresql/data
# #     environment:
# #       POSTGRES_USER: postgres
# #       POSTGRES_DB: postgres
# #       POSTGRES_PASSWORD: postgres

# #     # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
# #     # (Adding the "ports" property to this file will not forward from a Codespace.)

# volumes:
#   postgres-data:
